//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.0.3-b01-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2023.09.12 at 05:26:54 PM TRT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.webservicesoap.org/birthday", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.webservicesoap.birthday;
